### ISSUE TITLE
Search/Find doesn't work

### ISSUE THREAD

**Issue by lipisak** [F0rce/ace#14]
Hi @F0rce,
Sorry to bother you but we found another issue. The search feature doesn't work.

Editor doesn't respond to CMD+F or CTRL+F shortcut. It was working in 1.0.1 version.

Could you please check it?

Thx
JS

**Comment by lipisak** [comment]
Hi @F0rce ,
it works with newer Vaadin (14.6.5). So I close this issue.

JS

**Comment by F0rce** [comment]
When publishing a new Version of the Ace Editor I always test it with the newest Vaadin 14.x.x version. So using the latest one is always a good idea. Thanks for closing the issues.
