### ISSUE TITLE
Add a way to set custom completition and keep  'keyWordCompleter' and 'snippetCompleter'

### ISSUE THREAD

**Issue by danijelz** [F0rce/ace#2]
Currently the use of custom auto completion removes the  'keyWordCompleter' and 'snippetCompleter' from completers array and only 'staticWordCompleter' is used [(lit-ace.js).](https://github.com/F0rce/lit-ace/blob/c6e8d5de7b72d72bcfca2491e4d7e899f4f8d788/lit-ace.js#L366) Would it be possible to add another parameter to 'setCustomAutoCompletion' methods by which users can decide to keep the 'keyWordCompleter' and 'snippetCompleter' or maybe add methods like 'addCustomAutoCompletion' which would keep the 'keyWordCompleter' and 'snippetCompleter' and add the custom one?

**Comment by F0rce** [comment]
Hello Danijelz,

my solution for this feature request would be:
- add a boolean parameter to `addCustomAutoCompletion()` for keeping the snippetCompleter and staticWordCompleter

Would that fit your request?

David

**Comment by danijelz** [comment]
That would be perfect. Thanks for fast reply.

**Comment by F0rce** [comment]
this commit has been reverted!

i'm still working on those changes

**Comment by F0rce** [comment]
I think I will release the customAutoCompletion changes later today, and investigate #3 later on.

**Comment by F0rce** [comment]
one short question @danijelz 

what version are you using? latest (1.1.0) or 1.0.1 ? just curious

**Comment by danijelz** [comment]
I'm using 1.0.1 but i'll switch to 1.1.0 right now and let you know how it works...

**Comment by F0rce** [comment]
the customAutoCompletion Changes will be implemented in v1.1.1 (if you mean that).

**Comment by danijelz** [comment]
I tested and closed issue. Works perfectly.
