### ISSUE TITLE
aceEditor.setPlaceholder("some text"); is not working

### ISSUE THREAD

**Issue by KingFalse** [F0rce/ace#22]
**Describe the bug**
aceEditor.setPlaceholder("some text"); is not working,Not showing up
I tried version 1.3.1 and 1.3.2

**Comment by F0rce** [comment]
Hello @KingFalse,

in all of my tests the placeholder works as intended.

Could you please check if your Editor contains a "tab" or some wierd whitespaces ?

The editor has to be completely clear to see the placeholder.

Have a great day,
David

**Comment by F0rce** [comment]
If possible could you provide your source code for the ace editor:

Maybe I can spot some wrong configuration.

**Comment by F0rce** [comment]
Closed due to inactivity. Please re-open if you need further assistance.
