### ISSUE TITLE
Documentation page is offline

### ISSUE THREAD

**Issue by Koboo** [F0rce/ace#23]
**Description**
The Webpage docs.f0rce.de/ace is offline.

**Reproduce**
1. Open your favorite Browser
2. Enter `docs.f0rce.de/ace`
3. Press `Enter`

**Expected behavior**
A really beautifulö and helpful documentation should appear.

**Screenshots**
![Error-Screen](https://user-images.githubusercontent.com/14143908/149512142-2c466b9b-0ea0-464f-a8c3-b1d138a2d552.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Brave (Chromium, newest)

**Additional context**
Thanks for the amazing work on this addon! I hab struggle with the implentation, because of the offline documentation page, but with looking into the source of the documentation I got it to work like I want! :)

**Comment by F0rce** [comment]
@Koboo I am sorry for any inconvenice caused but if you go to https://docs.f0rce.de there is a message that I am moving the full documentation to GitHub Pages (and giving them a big overhaul). I hope I will be done in the next few days...

Have a great weekend,
David

**Comment by F0rce** [comment]
@Koboo https://docs.f0rce.de/ace is now fulle reachable and transfered to GitHub Pages. Hopefully I haven't caused that much of an inconvenience.
