### ISSUE TITLE
Half initialised editor in Chrome/no syntax highlightning

### ISSUE THREAD

**Issue by pellmann** [F0rce/ace#24]
**Describe the bug**
I used an other/old version of Ace for Vaadin Flow. Now I changed everything to Ace 1.3.4. It looks much more complete and is based in lit and I like it! The problem is, that in Chrome (96.0.4664.110 on OSX) and also in Brave (Version 1.34.80, Chromium: 97.0.4692.71 on OSX) the Component seems to not be really ready. It does not have syntax highlightning and also I noticed, it does not have a border.

It does not change anything if I call the Ace Menu (Cmd,) and change e.g. the syntax.

It is okay - with syntax highlightning and a border - after I switch views in my application. This switch sets components (parents of parents of the Ace Editor) unvisibel and visible again. 

In Firefox the problem does not occur at all. 

**To Reproduce**
If needed I can try to create a Vaadin App to reproduce?

**Screenshots**
Not working:
<img width="868" alt="Bildschirmfoto 2022-01-18 um 12 55 26" src="https://user-images.githubusercontent.com/12810428/149934546-cc6ee443-5ede-42df-9d55-b0d7c2bcf637.png">

After switching views to an other and back:
<img width="851" alt="Bildschirmfoto 2022-01-18 um 12 55 40" src="https://user-images.githubusercontent.com/12810428/149934693-28702504-ffe7-4a4c-a121-10aa6e5f24e0.png">

**Desktop (please complete the following information):**
 - Chrome (96.0.4664.110 on OSX)
 - Brave (Version 1.34.80, Chromium: 97.0.4692.71)

**Comment by F0rce** [comment]
Hello @pellmann,

This seems like an super odd issue, that I have never seen before. But let's try to sort it out.

Could you please tell me the Vaadin Version you are using?
And if it is possible, could you please upload a simple vaadin starter that (hopefully) displays the problem, so I could investigate further (GitHub would be the ideal place therefore).

Thanks in advance,
David

**Comment by pellmann** [comment]
Hi @F0rce, the Vaadin version is 14.8.1 - I will try to create something to reproduce, tomorrow. Thank you!

**Comment by pellmann** [comment]
Hi @F0rce, after I tried to reproduce with a new project and did not succeeded.. I rebuild my initial one with production mode on (which I think I have also tried before) and now I can not reproduce it any longer.. also not without production mode., good for me, but sorry for the wrong alarm.

**Comment by F0rce** [comment]
No worries, I am happy that the proplem was resolved (by itself).

Have a great time and thanks for the star,
David
