### ISSUE TITLE
Version 1.1.0 doesn't work with recent Vaadin version (14.5.2)

### ISSUE THREAD

**Issue by lipisak** [F0rce/ace#4]
Whenever I use version 1.1.0 of this plugin with Vaadin 14.5.2 the compilation doesn't work (Client compilation)
It seems that js files are not found by Vaadin compiler - there are many errors like following:

`ERROR in ../node_modules/.pnpm/ace-builds@1.4.12/node_modules/ace-builds/webpack-resolver.js?babel-target=es6
Module not found: Error: Can't resolve './src-noconflict/snippets/nginx.js&babel-target=es6' in '/***PATH_TO_WORKING_DIR***/node_modules/.pnpm/ace-builds@1.4.12/node_modules/ace-builds'
 @ ../node_modules/.pnpm/ace-builds@1.4.12/node_modules/ace-builds/webpack-resolver.js?babel-target=es6 343:46-118
 @ ../node_modules/.pnpm/@f0rce/lit-ace@1.1.1_webpack@4.42.0/node_modules/@f0rce/lit-ace/lit-ace.js?babel-target=es6
 @ ../target/frontend/generated-flow-imports.js?babel-target=es6`

All Vaadin dependencies in our application are provided by common maven parent - the same parent that provides ace plugin dependency.

Version 1.0.1 works with Vaadin 14.5.2 correctly.

Compilation fails even in building environment so it's not the matter of cache or incorrect node_modules folder.

**Comment by F0rce** [comment]
Hello Lipisak,

could you try to get v1.1.0 running, when using 14.5.1 ? I've been publishing the Add-on with version 14.5.1 in the pom.

I'll surely investigate what is happening there.

Have a great day,
David

**Comment by lipisak** [comment]
Hello,
I tried with 14.5.3 and it doesn't work either. There are some changes with pnpm in this version of vaadin, but nothing changed. Recently I don't have much time to test with 14.5.1 because I would have to revert our parent we use for all Vaadin libraries and production application. But I will try to do so at the weekend with simple maven project with that 14.5.1 parent.

JS

**Comment by nrapel** [comment]
I've tried on 14.5.1 and still has the same error. Although it works perfect when on development, when trying to create the production code the following errors appear and the production built stops.

**Comment by lipisak** [comment]
I've looked into your last commit (version 1.1.0) in master branch...couldn't the error be caused by removal of entry in pom.xml??? I don't see any other suspicious changes - bumping of frontend libraries, pure java changes...
But that was just quick look :)

**Comment by F0rce** [comment]
Thanks for the input @nrapel @lipisak 

I really think the error comes from that... I don't really know why I removed that in first place. I didn't found time to resolve all current issues but I'll try to publish everything as fast as possible. As a current workaround, please just stick to the older version.

Have a great day,
David

**Comment by mheicke** [comment]
Hey, @F0rce an updated version would be highly appreciated. Is there any way we can support you with it?
Cheers, Matthias

**Comment by F0rce** [comment]
Hei @mheicke,

thank you very much for your nice offer, but I think I got it. I was in school last week and I was able to fix some issues internally. Im currently pretty busy with projects at work so ill post-pons more testing and releasing by the end of the week. If I find something where I need help, I'll be sure to let you know.

Have a great week,
David

**Comment by F0rce** [comment]
Everything has been fixed locally on my computer. It was really a pain in the ass. But I'm happy to bring a full functional version of the ace editor super soon 👋🏻 

![grafik](https://user-images.githubusercontent.com/60381251/118344558-0a8c7680-b52f-11eb-9c0f-966fd3f5d6f2.png)

Packaged with `mvn package -Pproduction`
