### ISSUE TITLE
Backward selection isn't working when selection crosses lines

### ISSUE THREAD

**Issue by danijelz** [F0rce/ace#5]
**Describe the bug**
When trying to select text bachward from some point, the selection becomes invalid when crossing the line. This happens either by using keyboard or mouse.

**To Reproduce**
1. Write something like 
```
select *
from   dataset
where  age > 30
```
2. Set cursor position to end of text.
3. Press shift and up key or start selecting with mouse upward.

**Screen recording**
https://user-images.githubusercontent.com/13315108/115686442-7b3dda00-a359-11eb-9641-336254de64f6.mp4

**Comment by F0rce** [comment]
Answers in https://github.com/F0rce/ace/issues/7
